spring:
  application:
    name: save-todo-user-service
  datasource:
    url: jdbc:mysql://localhost:3307/userdb
    driver-class-name: com.mysql.jdbc.Driver
    username: user
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
server:
  port: 8070
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

